config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :comments
  devise_for :users

  root "videos#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :video
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :file, FileUploader
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        @comment = current_user.comments.create(comment_params)
        @video = @comment.video
    end

    def destroy
        @comment = current_user.comments.find params[:id]
        @video = @comment.video
        @comment.destroy
    end

    private

    def comment_params

        params.require(:comment).permit(:body, :video_id)
    end

    
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
    @videos = @videos.where("title like ?", "%#{params[:q]}%") if params[:q].present?
    @videos = @videos.page(params[:page]).per(4)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video.increment!(:view_count)
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.user = current_user

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :description, :file, :image)
    end

    def check_owner
      redirect_to root_path unless @video.user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/create.js.erb
$("#comments").html("<%= j(render("videos/comments")) %>")

app/views/comments/destroy.js.erb
$("#comments").html("<%= j(render("videos/comments")) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Jadon TUBE</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script   src="https://code.jquery.com/jquery-3.5.1.slim.min.js"   integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="   crossorigin="anonymous"></script>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<body>
  <nav class="navbar">
    <a href="/" class="navbar-brand">
      <%= fa_icon "youtube-play", class: "text-danger mr-1" %>
      Jadon TUBE
    </a>
    <%= form_tag videos_path, method: :get, class: "form-linline" do %>
      <%= text_field_tag :q, params[:q], class: "form-control mr-2" %>
      <%= submit_tag "검색", class: "btn btn-danger" %>
    <% end %>
    <div>
    <% if current_user %>
    <%= link_to '업로드', new_video_path, class: "btn btn-danger"%>
    <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
    <% else  %>
    <%= link_to "로그인", new_user_session_path, class: "btn btn-outline-danger"%>
    <%= link_to "회원가입", new_user_registration_path, class: "btn btn-outline-danger"%>
    <% end %>
    
    </div>
  </nav>
  <div class="conatiner-fluid">
    <div class="card">
      <div class="card-body">
        <%= yield %>
      </div>
    </div>
  </div>
</body>

</html>

app/views/videos/_comments.html.erb
댓글 (<%= @video.comments.count %>)
<hr>
<% @video.comments.each do |comment| %>
작성자 : <%= comment.user.email %>, <%= time_ago_in_words comment.created_at %>전
<%= simple_format comment.body %>
<p><%= link_to "삭제", comment, method: :delete, remote: true, data:{confirm: "정말 삭제하시겠습니까?"} if current_user && (current_user == comment.user)%></p>
<% end %>
<%= form_for Comment.new, remote: true do |f| %>
<div class="form_group">
    <%= f.hidden_field :video_id, value: @video.id %>
    <%= f.text_area :body, class: "form-control" %>
    <%= f.submit "작성", class: "btn btn-danger"%>
</div>
<% end %>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
<% if video.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

  <ul>
    <% video.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= form.label :title %>
  <%= form.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :description %>
  <%= form.text_area :description, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :file %>
  <%= form.file_field :file, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :image %>
  <%= form.file_field :image, class: "form-control" %>
</div>



<div class="actions">
  <%= form.submit "등록", class:"btn btn-danger"%>
</div>
<% end %>

app/views/videos/_video.html.erb
<div class="col-3 mb-3">
    <div class="card">
    <%= image_tag video.image.url, class:"w-100" if video.image? %>
        <div class="card-body">
        <%= link_to video, class: "text-dark" do %>
            <strong><%= video.title %></strong>
            <p class="small"><%= truncate video.description, length: 30 %></p>
            <p class="text-gray small"><%= time_ago_in_words video.created_at %>전, 조회수 <%=video.view_count.to_i%>회</p>
        <% end%>
        </div>
    </div>
</div>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<div class="row">
  <%= render @videos %>
</div>
<%= paginate @videos %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<%= video_tag @video.file.url, controls: true, class:"w-100" if @video.file? %>

<h4>
  <%= @video.title %>
</h4>
작성자 : <%= @video.user.email %>
<%= simple_format @video.description %>

조회수 : <%= @video.view_count.to_i %>

<br>
<% if current_user && (@video.user == current_user) %>
<%= link_to '수정', edit_video_path(@video), class: "btn btn-danger"%>
<%= link_to '삭제', @video, method: :delete, data: {confirm: "정말로 삭제하시겠습니까?"}, class: "btn btn-outline-danger" %>
<% end %>
<br><br>
<div id="comments">
<%= render "videos/comments" %>

</div>